@TravelAgencyAPI_HostAddress = http://localhost:5058

GET {{TravelAgencyAPI_HostAddress}}/weatherforecast/
Accept: application/json

GET {{TravelAgencyAPI_HostAddress}}/clients/
Accept: application/json

GET {{TravelAgencyAPI_HostAddress}}/trips/
Accept: application/json

###
